Repository jonx8/Summer_Practice, pull requests merged in 2023-07, with the labels that each got.

#15 Add report with specification and plan
  report.pdf
Labels: documentation

#16 Done algorithmic part
  pom.xml
  src/main/kotlin/ru/etu/visualkruskal/Edge.kt
  src/main/kotlin/ru/etu/visualkruskal/EdgeState.kt
  src/main/kotlin/ru/etu/visualkruskal/Kruskal.kt
Labels: enhancement

#20 Add KruskalTest
  pom.xml
  src/main/kotlin/ru/etu/visualkruskal/Kruskal.kt
  src/test/kotlin/KruskalTest.kt
Labels: tests

#22 Added GUI prototype
  src/main/kotlin/ru/etu/visualkruskal/AlgorithmState.kt
  src/main/kotlin/ru/etu/visualkruskal/DrawEdge.kt
  src/main/kotlin/ru/etu/visualkruskal/DrawVertex.kt
  src/main/kotlin/ru/etu/visualkruskal/HelloController.kt
  src/main/kotlin/ru/etu/visualkruskal/KruskalWrapper.kt
  src/main/kotlin/ru/etu/visualkruskal/Main.kt
  src/main/kotlin/ru/etu/visualkruskal/MainController.kt
  src/main/resources/ru/etu/visualkruskal/hello-view.fxml
  src/main/resources/ru/etu/visualkruskal/main-view.fxml
  src/main/resources/ru/etu/visualkruskal/menuButtonStyle.css
Labels: enhancement

#24 Fixed MenuButton width
  src/main/resources/ru/etu/visualkruskal/main-view.fxml
Labels: bug

#25 Realized reading graph from file
  src/main/kotlin/ru/etu/visualkruskal/Kruskal.kt
  src/main/kotlin/ru/etu/visualkruskal/KruskalWrapper.kt
  src/main/kotlin/ru/etu/visualkruskal/MainController.kt
Labels: enhancement

#27 Add graphical editing of graph
  src/main/kotlin/ru/etu/visualkruskal/AlgorithmState.kt
  src/main/kotlin/ru/etu/visualkruskal/DrawEdge.kt
  src/main/kotlin/ru/etu/visualkruskal/DrawVertex.kt
  src/main/kotlin/ru/etu/visualkruskal/KruskalWrapper.kt
  src/main/kotlin/ru/etu/visualkruskal/MainController.kt
  src/main/resources/ru/etu/visualkruskal/main-view.fxml
Labels: enhancement

#29 Fixed one vertex bug
  src/main/kotlin/ru/etu/visualkruskal/KruskalWrapper.kt
  src/main/kotlin/ru/etu/visualkruskal/MainController.kt
Labels: bug

#35 Added file manager window
  src/main/kotlin/ru/etu/visualkruskal/MainController.kt
  src/main/resources/ru/etu/visualkruskal/main-view.fxml
Labels: enhancement

#36 Add background for weights
  src/main/kotlin/ru/etu/visualkruskal/DrawEdge.kt
  src/main/kotlin/ru/etu/visualkruskal/KruskalWrapper.kt
  src/main/kotlin/ru/etu/visualkruskal/MainController.kt
Labels: bug

#40 Add background for multi-digit weights
  src/main/kotlin/ru/etu/visualkruskal/DrawEdge.kt
Labels: bug

#41 Add full version of the report
  report.pdf
Labels: documentation
